
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 21 19:38:26 CET 2016
//----------------------------------------------------

package nzikic.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 21;
  public static final int CONST = 16;
  public static final int GE = 32;
  public static final int STRCONST = 42;
  public static final int LPAREN = 19;
  public static final int SEMI = 4;
  public static final int MINUS = 25;
  public static final int RPAREN = 20;
  public static final int AND = 35;
  public static final int LT = 33;
  public static final int OR = 36;
  public static final int COMMA = 3;
  public static final int CLASS = 8;
  public static final int INC = 37;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int ASSIGN = 23;
  public static final int IF = 9;
  public static final int DOT = 39;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int RBRACKET = 22;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int NUMBER = 40;
  public static final int MOD = 28;
  public static final int NEQ = 30;
  public static final int IDENT = 41;
  public static final int BREAK = 14;
  public static final int VOID = 7;
  public static final int EQ = 29;
  public static final int LBRACE = 17;
  public static final int ELSE = 10;
  public static final int READ = 12;
  public static final int CHARCONST = 44;
  public static final int WHILE = 13;
  public static final int RBRACE = 18;
  public static final int BOOLCONST = 43;
  public static final int EXTENDS = 15;
  public static final int DEC = 38;
  public static final int GT = 31;
  public static final int PRINT = 5;
}

